# Generated by Django 6.0.2 on 2026-02-18 14:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anomaly_type', models.CharField(choices=[('spike', 'Usage Spike'), ('drop', 'Usage Drop'), ('gap', 'Reading Gap'), ('negative', 'Negative Reading'), ('flatline', 'Flatline')], max_length=15)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('detected_at', models.DateTimeField()),
                ('value_kwh', models.DecimalField(blank=True, decimal_places=4, help_text='The anomalous reading value', max_digits=12, null=True)),
                ('expected_kwh', models.DecimalField(blank=True, decimal_places=4, help_text='The expected normal value', max_digits=12, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='customers.meter')),
            ],
            options={
                'verbose_name_plural': 'anomalies',
                'ordering': ['-detected_at'],
            },
        ),
    ]
