# Generated by Django 6.0.2 on 2026-02-18 13:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=10)),
                ('property_type', models.CharField(choices=[('house', 'House'), ('flat', 'Flat'), ('bungalow', 'Bungalow'), ('commercial', 'Commercial'), ('other', 'Other')], default='house', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='customers.customer')),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ['postcode'],
            },
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mpan', models.CharField(help_text='Meter Point Administration Number (electricity) or Meter Point Reference Number (gas)', max_length=21, unique=True, verbose_name='MPAN / MPRN')),
                ('serial_number', models.CharField(max_length=20)),
                ('fuel_type', models.CharField(choices=[('electricity', 'Electricity'), ('gas', 'Gas')], max_length=15)),
                ('is_smart', models.BooleanField(default=False)),
                ('installed_on', models.DateField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='customers.property')),
            ],
            options={
                'ordering': ['mpan'],
            },
        ),
    ]
