# Generated by Django 6.0.2 on 2026-02-18 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_at', models.DateTimeField(db_index=True)),
                ('value_kwh', models.DecimalField(decimal_places=4, max_digits=12)),
                ('reading_type', models.CharField(choices=[('actual', 'Actual'), ('estimated', 'Estimated')], default='actual', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='customers.meter')),
            ],
            options={
                'ordering': ['-reading_at'],
                'indexes': [models.Index(fields=['meter', 'reading_at'], name='metering_me_meter_i_bf7637_idx')],
            },
        ),
    ]
