# Generated by Django 6.0.2 on 2026-02-18 13:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('fuel_type', models.CharField(choices=[('electricity', 'Electricity'), ('gas', 'Gas')], max_length=15)),
                ('tariff_type', models.CharField(choices=[('fixed', 'Fixed'), ('variable', 'Variable'), ('time_of_use', 'Time of Use')], default='variable', max_length=15)),
                ('standing_charge_pence', models.DecimalField(decimal_places=4, help_text='Daily standing charge in pence', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='RateBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text="e.g. 'Peak', 'Off-peak', 'Standard'", max_length=50)),
                ('start_time', models.TimeField(blank=True, help_text='Null for flat-rate tariffs', null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('rate_pence_per_kwh', models.DecimalField(decimal_places=4, help_text='Unit rate in pence per kWh', max_digits=8)),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_bands', to='tariffs.tariff')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='CustomerTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_assignments', to='customers.customer')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_assignments', to='tariffs.tariff')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
    ]
