# Generated by Django 6.0.2 on 2026-02-18 13:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('tariffs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('void', 'Void')], default='draft', max_length=10)),
                ('total_kwh', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('standing_charge_pence', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usage_charge_pence', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount_pence', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='customers.customer')),
            ],
            options={
                'ordering': ['-period_start'],
                'unique_together': {('customer', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='BillLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('rate_band_label', models.CharField(blank=True, max_length=50)),
                ('kwh', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('rate_pence_per_kwh', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('amount_pence', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='billing.bill')),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.meter')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tariffs.tariff')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
