# Generated by Django 6.0.2 on 2026-02-18 13:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('granularity', models.CharField(choices=[('half_hourly', 'Half-hourly'), ('hourly', 'Hourly'), ('daily', 'Daily')], default='half_hourly', max_length=15)),
                ('forecast_start', models.DateTimeField()),
                ('forecast_end', models.DateTimeField()),
                ('lookback_days', models.PositiveIntegerField(default=7, help_text='Number of historical days used for the prediction')),
                ('total_predicted_kwh', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='customers.meter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('predicted_kwh', models.DecimalField(decimal_places=4, max_digits=12)),
                ('lower_bound_kwh', models.DecimalField(decimal_places=4, max_digits=12)),
                ('upper_bound_kwh', models.DecimalField(decimal_places=4, max_digits=12)),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='forecasting.demandforecast')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
